[tool.poetry]
name = "benchmark-run-config"
version = "0.1.0"
description = ""
authors = ["Anton Shiryaev <a.shiryaev@cashalot.mcfef.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
